// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBIHvro9tnO7uWDPzeMJm42kj1C-jvTg',
    appId: '1:1095312732170:web:565232d130365d76ee2ff3',
    messagingSenderId: '1095312732170',
    projectId: 'fir-authapp-ca0ac',
    authDomain: 'fir-authapp-ca0ac.firebaseapp.com',
    storageBucket: 'fir-authapp-ca0ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70CvaY3JcmYTOhfZyXLeRuvui4RTVGHQ',
    appId: '1:1095312732170:android:704184ac642637dbee2ff3',
    messagingSenderId: '1095312732170',
    projectId: 'fir-authapp-ca0ac',
    storageBucket: 'fir-authapp-ca0ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVEaoClVr1T0aY5Of-n5mUQqTDsYZW__c',
    appId: '1:1095312732170:ios:8d78d8a43860f298ee2ff3',
    messagingSenderId: '1095312732170',
    projectId: 'fir-authapp-ca0ac',
    storageBucket: 'fir-authapp-ca0ac.firebasestorage.app',
    iosBundleId: 'com.neel.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVEaoClVr1T0aY5Of-n5mUQqTDsYZW__c',
    appId: '1:1095312732170:ios:8d78d8a43860f298ee2ff3',
    messagingSenderId: '1095312732170',
    projectId: 'fir-authapp-ca0ac',
    storageBucket: 'fir-authapp-ca0ac.firebasestorage.app',
    iosBundleId: 'com.neel.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBIHvro9tnO7uWDPzeMJm42kj1C-jvTg',
    appId: '1:1095312732170:web:5f560c78c4e655c6ee2ff3',
    messagingSenderId: '1095312732170',
    projectId: 'fir-authapp-ca0ac',
    authDomain: 'fir-authapp-ca0ac.firebaseapp.com',
    storageBucket: 'fir-authapp-ca0ac.firebasestorage.app',
  );
}
